{{- if .Values.worker.enabled }}
{{- if .Values.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: streamtransfer-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: streamtransfer-editor
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
