/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapiserver "github.com/GIT_USER_ID/GIT_REPO_ID/openapiserver"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := openapiserver.NewDefaultApiService()
	DefaultApiController := openapiserver.NewDefaultApiController(DefaultApiService)

	router := openapiserver.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8081", router))
}
