/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

// openapi "github.com/mesh-for-data/mesh-for-data/pkg/connectors/out_go_server/go"

func main() {
	// log.Printf("Server started")

	// DefaultApiService := openapi.NewDefaultApiService()
	// DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	// router := openapi.NewRouter(DefaultApiController)

	// log.Fatal(http.ListenAndServe(":8080", router))
}
