/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PolicymanagerResponse - This taxonomy defines the structure of response received from policymanager with enforcements.
type PolicymanagerResponse struct {

	// This is the id returned by the governance engine
	DecisionId string `json:"decision_id,omitempty"`

	// While showing the result, action contains the action type and the associated entity on which action has been taken.
	Result []PolicymanagerResponseResult `json:"result"`
}
