/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResourceColumns struct {

	// name of column or component
	Name string `json:"name"`

	Tags map[string]map[string]interface{} `json:"tags,omitempty"`
}
