/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GeographyName : Name of the geography
type GeographyName string

// List of GeographyName
const (
	NETHERLANDS GeographyName = "Netherlands"
	TURKEY GeographyName = "Turkey"
)
