/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Resource - Data set or other type of resource.
type Resource struct {

	// Name of the data set
	Name string `json:"name"`

	// location of dataset credentials
	Creds string `json:"creds"`

	Tags map[string]map[string]interface{} `json:"tags,omitempty"`

	// List of column names in the data set with their associated tags. They must be key value pairs.
	Columns []ResourceColumns `json:"columns,omitempty"`
}
