/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	openapiclient "github.com/mesh-for-data/mesh-for-data/pkg/connectors/out_go_client"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// GetPoliciesDecisions - getPoliciesDecisions
func (s *DefaultApiService) GetPoliciesDecisions(ctx context.Context, input []openapiclient.PolicymanagerRequest) (ImplResponse, error) {
	fmt.Println("Reached Server!")
	fmt.Println("input")
	fmt.Println(input)
	// TODO - update GetPoliciesDecisions with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []PolicymanagerResponse{}) or use other options such as http.Ok ...
	//return Response(200, []PolicymanagerResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPoliciesDecisions method not implemented")
}
