/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Action - The action being requested on the data (ex: read, write...) and the geography in which it is to take place.
type Action struct {

	ActionType ActionType `json:"action_type"`

	ProcessingLocation GeographyName `json:"processingLocation,omitempty"`
}
