/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Role : The position of the person in the organization processing the data.
type Role string

// List of Role
const (
	SALES Role = "Sales"
	HR Role = "HR"
	CUSTOMER_SUPPORT_EXECUTIVE Role = "Customer Support Executive"
	BUSINESS_ANALYST Role = "Business Analyst"
	DATA_SCIENTIST Role = "Data Scientist"
)
