/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AllowableActionColumns string

// List of AllowableActionColumns
const (
	REMOVE_COLUMN AllowableActionColumns = "RemoveColumn"
	REDACT_COLUMN AllowableActionColumns = "RedactColumn"
	ENCRYPT_COLUMN AllowableActionColumns = "EncryptColumn"
	PERIODIC_BLACKOUT AllowableActionColumns = "PeriodicBlackout"
)
