/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ActionType : The action to be taken on the data.  A mandatory object used by the M4D controller's logic
type ActionType string

// List of ActionType
const (
	READ ActionType = "read"
	WRITE ActionType = "write"
	DELETE ActionType = "delete"
)
