/*
 * Some Swagger
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Intent : The reason for which the data is to be used.
type Intent string

// List of Intent
const (
	MARKETING Intent = "Marketing"
	CUSTOMER_SUPPORT Intent = "Customer Support"
	FRAUD_DETECTION Intent = "Fraud Detection"
	CUSTOMER_BEHAVIOR_ANALYSIS Intent = "Customer Behavior Analysis"
)
