openapi: 3.0.1
info:
  version: 1.0.0
  title: Some Swagger
  license:
    name: MIT
servers:
  - url: https://localhost:8080
paths:
  /getPoliciesDecisions:
    get:
      summary: getPoliciesDecisions
      description: Multiple status values can be provided with comma separated strings
      operationId: getPoliciesDecisions
      parameters:
        - name: input
          description: input values that need to be considered for filter
          required: true
          in: query
          content:
            application/json:
              schema:
                type: object
                $ref: policymanager_request.structs.schema.json
        - name: creds
          description: credentials to wkc connector
          required: true
          in: query
          schema:
            type: string                
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: policymanager_response.structs.schema.json
        '400':
          description: Invalid status value
