openapi: 3.0.1
info:
  version: 1.0.0
  title: Data Catalog Service - Asset Details
  license:
    name: Apache 2.0
servers:
  - url: https://localhost:8080
paths:
  /getAssetInfo:
      post:
        summary: This REST API gets data asset information from the data catalog configured in fybrik for the data sets indicated in FybrikApplication yaml
        operationId: getAssetInfo
        parameters:
          - in: header
            name: X-Request-Datacatalog-Cred
            schema:
              type: string
            required: true
        requestBody:
          description: Data Catalog Request Object.
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/GetAssetRequest"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/GetAssetResponse"
          '400':
            description: Bad request - server cannot process the request due to client error

  /writeAssetInfo:
      post:
        summary: This REST API write data asset information to the data catalog configured in fybrik
        operationId: writeAssetInfo
        parameters:
          - in: header
            name: X-Request-Datacatalog-Write-Cred
            schema:
              type: string
            required: true
        requestBody:
          description: Write Asset Request
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/WriteAssetRequest"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/WriteAssetResponse"
          '400':
            description: Bad request - server cannot process the request due to client error