openapi: 3.0.1
info:
  version: 1.0.0
  title: Data Catalog Service - Asset Details
  license:
    name: Apache 2.0
servers:
  - url: https://localhost:8080
paths:
  /getAssetInfo:
      post:
        summary: This REST API gets data asset information from the data catalog configured in fybrik for the data sets indicated in FybrikApplication yaml
        operationId: getAssetInfo
        parameters:
          - in: header
            name: X-Request-Datacatalog-Cred
            description: This header carries credential information related to relevant catalog from which the asset information needs to be retrieved.
            schema:
              type: string
            required: true
        requestBody:
          description: Data Catalog Request Object.
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/GetAssetRequest"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/GetAssetResponse"
          '400':
            description: Bad request - server cannot process the request due to client error


  /createAsset:
      post:
        summary: This REST API writes data asset information to the data catalog configured in fybrik
        operationId: createAsset
        parameters:
          - in: header
            name: X-Request-Datacatalog-Write-Cred
            description: This header carries credential information related to accessing the relevant destination catalog.
            schema:
              type: string
            required: true
        requestBody:
          description: Write Asset Request
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/CreateAssetRequest"
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/CreateAssetResponse"
          '400':
            description: Bad request - server cannot process the request due to client error

  /deleteAsset:
      delete:
        summary: This REST API deletes data asset
        operationId: deleteAsset
        parameters:
          - in: header
            name: X-Request-Datacatalog-Cred
            description: This header carries credential information related to relevant catalog from which the asset information needs to be retrieved.
            schema:
              type: string
            required: true
        requestBody:
          description: Delete Asset Request
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/DeleteAssetRequest"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/DeleteAssetResponse"
          '400':
            description: Bad request - server cannot process the request due to client error
          '404':
            description: id not found
          '401':
            description: Unauthorized

  /updateAsset:
      patch:
        summary: This REST API updates data asset information in the data catalog configured in fybrik
        operationId: updateAsset
        parameters:
          - in: header
            name: X-Request-Datacatalog-Update-Cred
            description: This header carries credential information related to accessing the relevant destination catalog.
            schema:
              type: string
            required: true
        requestBody:
          description: Update Asset Request
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/UpdateAssetRequest"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/UpdateAssetResponse"
          '400':
            description: Bad request - server cannot process the request due to client error
          '404':
            description: id not found
          '401':
            description: Unauthorized

  /createNewComponent:
      patch:
        summary: This REST API is a test method
        operationId: createNewComponent
        parameters:
          - in: header
            name: X-Request-CreateNewComponent-Cred
            description: This header carries credential information.
            schema:
              type: string
            required: true
        requestBody:
          description: create new component
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/CreateNewComponentRequest"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/datacatalog.json#/definitions/CreateNewComponentResponse"
          '400':
            description: Bad request - server cannot process the request due to client error
          '404':
            description: id not found
          '401':
            description: Unauthorized